### ISSUE TITLE
Peer review on jest-testing

### ISSUE THREAD

**Issue by jerryowusu** [Dagic-zewdu/Todo-list#6]
Congrats Dagic, for a job well done. However we saw a few issues that we would like you to check, hopefully it can help improve your code.

- [ ] On line 13 of the action.test.js file, it would be more comprehensive if you could use <code>(key === 'index' || key === 'completed' || key === 'description')</code>  instead of  <code>(key === 'index' || key !== 'completed' || key !== 'description')</code>.

- [ ] Also on line 16 of the same file, it would be more understandable if you could use <code>(todo.description.toString().length > 0) </code> instead of <code>(todo.description.length !== 0) </code>

**Comment by Dagic-zewdu** [comment]
Thanks for your comment jerry.I think the issues are fixed now.
